server.port=8080

# App config
language.analyzer=japanese
trainer.config.file=./trainer-config.json

# AnkiConnect
ankiconnect.url=http://localhost:8765
ankiconnect.version=6

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG
logging.level.com.ankitrainer=DEBUG