server.port=8080

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/anki_trainer
spring.datasource.username=anki_trainer
spring.datasource.password=password
spring.jpa.properties.hibernate.default_schema=anki_trainer
spring.datasource.driver-class-name=org.postgresql.Driver
jpa.hibernate.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
jpa.hibernate.ddl-auto=validate
spring.sql.init.schema-locations=classpath:sql/init.sql

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

jpa.hibernate.properties.hibernate.format_sql=true
jpa.hibernate.show-sql=true

# App config
#language.analyzer=japanese
#trainer.config.file=./trainer-config.json

# AnkiConnect
ankiconnect.url=http://localhost:8765
ankiconnect.version=6

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG
logging.level.com.ankitrainer=DEBUG
spring.messages.basename=messages